import Head from 'next/head';
import Image from 'next/image';
import styles from '@/styles/Home.module.css';
import { useAuth } from '@/lib/auth';

export default function Home() {
  const { user, signinWithGitHub, signout } = useAuth();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.center}>
          <h1>Fast Feedback</h1>
        </div>

        {user?.name}
        {user ? (
          <button onClick={() => signout()}>Sign Out</button>
        ) : (
          <button onClick={() => signinWithGitHub()}>Sign In</button>
        )}
      </main>
    </>
  );
}
